[default]
id="default"
base_potential = 0.15
line_exponent = 1.5
max_multiplier = 1.5
weight_best = 0.6
weight_path = 0.4
max_score = 0.9
importance_win_weight = 2.0
importance_develop_weight = 0.3
importance_fresh_weight = 0.1
global_score_weight = 0.65
strategic_score_weight = 0.35
offensive_weight = 0.7
defensive_weight = 0.3
final_max_score = 0.9

[aggressive]
id="aggressive"
base_potential = 0.2
line_exponent = 1.8
max_multiplier = 1.7
weight_best = 0.7
weight_path = 0.3
max_score = 0.95
importance_win_weight = 2.0
importance_develop_weight = 0.3
importance_fresh_weight = 0.1
global_score_weight = 0.70
strategic_score_weight = 0.30
offensive_weight = 0.8
defensive_weight = 0.2
final_max_score = 0.95

[defensive]
id="defensive"
base_potential = 0.1
line_exponent = 1.2
max_multiplier = 1.3
weight_best = 0.5
weight_path = 0.5
max_score = 0.85
importance_win_weight = 2.0
importance_develop_weight = 0.3
importance_fresh_weight = 0.1
global_score_weight = 0.60
strategic_score_weight = 0.40
offensive_weight = 0.5
defensive_weight = 0.5
final_max_score = 0.85

