DEFAULT_BOT_ID = "default"


BASELINE_PRESETS = {
    "default": {
        "base_potential": 0.15,
        "line_exponent": 1.5,
        "max_multiplier": 1.5,
        "weight_best": 0.6,
        "weight_path": 0.4,
        "max_score": 0.9,
        "importance_win_weight": 2.0,
        "importance_develop_weight": 0.3,
        "importance_fresh_weight": 0.1,
        "global_score_weight": 0.6,
        "strategic_score_weight": 0.4,
        "offensive_weight": 0.5,
        "defensive_weight": 0.5,
        "final_max_score": 0.9,
        "ucb_constant": 1.414,
        "rollout_depth": 6,
    },
    "aggressive": {
        "base_potential": 0.2,
        "line_exponent": 1.8,
        "max_multiplier": 1.7,
        "weight_best": 0.7,
        "weight_path": 0.3,
        "max_score": 0.95,
        "importance_win_weight": 2.0,
        "importance_develop_weight": 0.3,
        "importance_fresh_weight": 0.1,
        "global_score_weight": 0.70,
        "strategic_score_weight": 0.30,
        "offensive_weight": 0.8,
        "defensive_weight": 0.2,
        "final_max_score": 0.95,
        "ucb_constant": 1.414,
        "rollout_depth": 6,
    },
    "defensive": {
        "base_potential": 0.1,
        "line_exponent": 1.2,
        "max_multiplier": 1.3,
        "weight_best": 0.5,
        "weight_path": 0.5,
        "max_score": 0.85,
        "importance_win_weight": 2.0,
        "importance_develop_weight": 0.3,
        "importance_fresh_weight": 0.1,
        "global_score_weight": 0.60,
        "strategic_score_weight": 0.40,
        "offensive_weight": 0.5,
        "defensive_weight": 0.5,
        "final_max_score": 0.85,
        "ucb_constant": 1.414,
        "rollout_depth": 6,
    },
    "global_focus": {
        "base_potential": 0.15,
        "line_exponent": 1.5,
        "max_multiplier": 1.5,
        "weight_best": 0.6,
        "weight_path": 0.4,
        "max_score": 0.9,
        "importance_win_weight": 2.0,
        "importance_develop_weight": 0.3,
        "importance_fresh_weight": 0.1,
        "global_score_weight": 0.75,
        "strategic_score_weight": 0.25,
        "offensive_weight": 0.5,
        "defensive_weight": 0.5,
        "final_max_score": 0.9,
        "ucb_constant": 1.414,
        "rollout_depth": 6,
    },
    "yielding": {
        "base_potential": 0.15,
        "line_exponent": 1.5,
        "max_multiplier": 1.5,
        "weight_best": 0.6,
        "weight_path": 0.4,
        "max_score": 0.9,
        "importance_win_weight": 2.0,
        "importance_develop_weight": 0.3,
        "importance_fresh_weight": 0.15,
        "global_score_weight": 0.65,
        "strategic_score_weight": 0.35,
        "offensive_weight": 0.4,
        "defensive_weight": 0.6,
        "final_max_score": 0.9,
        "ucb_constant": 1.414,
        "rollout_depth": 6,
    },
    "aggressive_yielding": {
        "base_potential": 0.2,
        "line_exponent": 1.8,
        "max_multiplier": 1.7,
        "weight_best": 0.7,
        "weight_path": 0.3,
        "max_score": 0.95,
        "importance_win_weight": 2.0,
        "importance_develop_weight": 0.3,
        "importance_fresh_weight": 0.15,
        "global_score_weight": 0.70,
        "strategic_score_weight": 0.30,
        "offensive_weight": 0.75,
        "defensive_weight": 0.3,
        "final_max_score": 0.95,
        "ucb_constant": 1.414,
        "rollout_depth": 6,
    },
    "draw_hater": {
        "base_potential": 0.15,
        "line_exponent": 1.5,
        "max_multiplier": 1.5,
        "weight_best": 0.6,
        "weight_path": 0.4,
        "max_score": 0.9,
        "importance_win_weight": 2.0,
        "importance_develop_weight": 0.3,
        "importance_fresh_weight": 0.1,
        "global_score_weight": 0.6,
        "strategic_score_weight": 0.4,
        "offensive_weight": 0.5,
        "defensive_weight": 0.5,
        "final_max_score": 0.9,
        "terminal_draw_value": 0.35,
        "ucb_constant": 1.414,
        "rollout_depth": 6,
    },
}

# New immutable baseline exact-endgame variants.
BASELINE_PRESETS["default_exact_legal10_draw050_v1"] = {
    **BASELINE_PRESETS["default"],
    "exact_endgame_legal_cells_threshold": 10,
    "terminal_draw_value": 0.5,
}
BASELINE_PRESETS["default_exact_legal14_draw050_v1"] = {
    **BASELINE_PRESETS["default"],
    "exact_endgame_legal_cells_threshold": 14,
    "terminal_draw_value": 0.5,
}
BASELINE_PRESETS["default_exact_legal10_draw025_v1"] = {
    **BASELINE_PRESETS["default"],
    "exact_endgame_legal_cells_threshold": 10,
    "terminal_draw_value": 0.25,
}


def get_preset(bot_id: str):
    return dict(BASELINE_PRESETS.get(bot_id, BASELINE_PRESETS[DEFAULT_BOT_ID]))
