# MCTS Configuration Parameters
DEFAULT_UCB_CONSTANT = 0.75
DEFAULT_SECONDS_LIMIT = 10
DEFAULT_NODE_LIMIT = 100000
DEFAULT_OPPONENT_NODE_LIMIT = 10000

# Time Thresholds
GREEDY_TIME_THRESHOLD = 1
MEDIUM_TIME_THRESHOLD = 5
MIN_TIME_RATIO = 0.25
CHECK_INTERVAL = 0.1

# Position Complexity Thresholds
COMPLEX_POSITION_THRESHOLD = 40
MEDIUM_POSITION_THRESHOLD = 20

# Early Stopping Parameters
CONFIDENCE_HIGH = 0.8
CONFIDENCE_MODERATE = 0.5
STABLE_CHECKS_HIGH = 5
STABLE_CHECKS_MODERATE = 10
STABLE_CHECKS_LOW = 15
SCORE_DIFF_NORMALIZER = 0.2

# Computation Distribution Settings
COMP_DIST_FEW_MOVES = [0.4, 0.8, 1.6]
COMP_DIST_MEDIUM_MOVES = [0.2, 0.4, 0.8]
COMP_DIST_MANY_MOVES = [0.1, 0.2, 0.4]